name: CI Pipeline

on:
  push:
    branches:
      - ci-actions
  pull_request:
    branches:
      - ci-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python3 venv dependencies
        run: sudo apt-get install -y python3-venv

      - name: Clean workspace
        run: rm -rf venv

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 3: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      # Step 4: Package the app as a zip file
    #   - name: Create artifact
    #     run: |
    #       timestamp=$(date +'%Y%m%d%H%M%S')
    #       zip -r address-book-python-$timestamp.zip .
    #     env:
    #       TIMESTAMP: ${{ github.run_id }}

    #   - name: Set TIMESTAMP
    #     run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    #   - name: Create zip artifact
    #     run: zip -r address-book-python-${{ env.TIMESTAMP }}.zip .

    #   - name: Verify artifact
    #     run: ls -la address-book-python-*.zip

    #   - name: Upload artifact to S3
    #     run: aws s3 cp address-book-python-${{ env.TIMESTAMP }}.zip s3://simartefacts/
    #     env:
    #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #         AWS_DEFAULT_REGION: us-east-1


      # Step 6: Send email notification
      - name: Send email notification
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
          https://api.mailgun.net/v3/devforge.cc/messages \
          -F from="CI Pipeline <mailgun@devforge.cc>" \
          -F to="o.oluwapelumi@gmail.com" \
          -F subject="CI Pipeline Status: Success" \
          -F text="The build artifact has been successfully created and uploaded to S3."\
          -w "\nHTTP Status Code: %{http_code}\n"
                  
